fix dependencies for Debian 8, do daemon-reload in start_server, we might not have the init script copied yet.

diff --git a/buildpkg b/buildpkg
--- a/buildpkg
+++ b/buildpkg
@@ -91,6 +91,17 @@ msg()
 # dependecies and global variables
 set_deps_and_vars()
 {
+ local distro_release=""
+
+ if [ -x /usr/bin/lsb_release ]; then
+    distro_release="$(/usr/bin/lsb_release -r -s 2>/dev/null)"
+ elif [ -r /etc/debian_version ]; then
+    distro_release="$(cat /etc/debian_version 2>/dev/null)"
+ else
+    msg error "unable to get version information, /etc/debian_version or /usr/bin/lsb_release are missing."
+    exit 1
+ fi
+
  # Do not modify this, this are the only supported applications.
  PACKAGES="mysql mongodb nginx fcgiwrap php php_mongo postfix greyfix dovecot spf clamav clamsmtp pam_mysql monit phpmyadmin awstats"
 
@@ -106,10 +117,15 @@ set_deps_and_vars()
  # NOTE: this will pull in mysql, nginx, php
  tmpl_extra=("monit" "phpmyadmin" "awstats")
 
- mysqldeps="build-essential cmake g++-4.4 intltool flex bison libtool libreadline-dev libncurses5-dev libjemalloc-dev \
+ mysqldeps="build-essential cmake g++ intltool flex bison libtool libreadline-dev libncurses5-dev libjemalloc-dev \
  libncursesw5-dev libbz2-dev zlib1g-dev libtool libaio-dev libssl-dev libevent-dev libxml2-dev libzmq-dev"
- mongodbdeps="scons g++-4.4 intltool binutils libpcap-dev libpcre3-dev libboost-dev libboost-program-options-dev \
- libboost-filesystem-dev libboost-thread-dev libreadline-dev libssl-dev libstdc++6-4.4-dev"
+ mongodbdeps="scons g++ intltool binutils libpcap-dev libpcre3-dev libboost-dev libboost-program-options-dev \
+ libboost-filesystem-dev libboost-thread-dev libreadline-dev libssl-dev"
+ if [ "$distro_release" ~= 8.* ]; then
+    mongodbdeps="$mongodbdeps libstdc++6-4.9-dev"
+ else
+    mongodbdeps="$mongodbdeps libstdc++6-4.7-dev"
+ fi
  nginxdeps="build-essential bzip2 libpcre3-dev libpcrecpp0 libssl-dev libbz2-dev zlib1g-dev intltool libperl-dev libaio-dev libcurl3-gnutls"
  fcgiwrapdeps="libfcgi-dev automake autoconf pkg-config libtool"
  phpdeps="build-essential libtool libmhash-dev libxml2-dev libltdl-dev libfontconfig1-dev libfreetype6-dev libgd2-noxpm-dev libmm-dev \
@@ -670,7 +686,6 @@ run_install()
  local logdir=$CWD/log
  local logfile=${logdir}/${name}-install.log
  local cmd=
- local systemd_cmd=
 
  if [ ${installoff} -eq 0 ]; then
     if [ $ID -ne 0 ]; then
@@ -705,19 +720,6 @@ run_install()
        $cmd make install >> ${logfile} 2>&1 || { msg error "Failed to install binary."; exit 1; }
     fi
 
-    systemd_cmd="none"
-    if [ -x "/bin/systemctl" ]; then
-       systemd_cmd="/bin/systemctl"
-    elif [ -x "/usr/bin/systemctl" ]; then
-       systemd_cmd="/usr/bin/systemctl"
-    fi
-
-    if [ "$systemd_cmd" == "none" ]; then
-       msg info "systemd not avaiable, skipping this part."
-    else
-       msg info "Running $systemd_cmd daemon-reload ..."
-       $cmd $systemd_cmd daemon-reload >/dev/null 2>&1 || msg warn "Fail to reload systemd manager configuration"
-    fi
  else
     msg warn "Package installation disabled from the command-line."
  fi 
@@ -994,9 +996,23 @@ start_service()
 {
  local name=$1
  local cmd=
+ local systemd_cmd="none"
 
  if [ $ID -ne 0 ]; then
     cmd="sudo"
+ fi
+
+ if [ -x "/bin/systemctl" ]; then
+    systemd_cmd="/bin/systemctl"
+ elif [ -x "/usr/bin/systemctl" ]; then
+    systemd_cmd="/usr/bin/systemctl"
+ fi
+
+ if [ "$systemd_cmd" == "none" ]; then
+    msg info "systemd not avaiable, skipping this part."
+ else
+    msg info "Running $systemd_cmd daemon-reload ..."
+    $cmd $systemd_cmd daemon-reload >/dev/null 2>&1 || msg warn "Fail to reload systemd manager configuration"
  fi
 
  if [ -e /etc/init.d/${name} ]; then
