added phpmyadmin has installable package, clean-up a bit the code.

diff --git a/buildpkg b/buildpkg
--- a/buildpkg
+++ b/buildpkg
@@ -5,7 +5,7 @@ VERSION=1.0.1
 CWD=$(pwd)
 
 # Do not modify this, this are the only supported applications.
-PACKAGES="mysql nginx php monit eaccelerator postfix greyfix dovecot spf clamav clamsmtp pam_mysql"
+PACKAGES="mysql nginx php monit eaccelerator postfix greyfix dovecot spf clamav clamsmtp pam_mysql phpmyadmin"
 
 mysqldeps="build-essential cmake g++-4.4 intltool flex bison libtool libreadline-dev libncurses5-dev libncursesw5-dev libbz2-dev zlib1g-dev libtool patch libaio-dev libssl-dev"
 nginxdeps="build-essential bzip2 libpcre3-dev libpcrecpp0 libssl-dev libbz2-dev zlib1g-dev intltool libperl-dev libaio-dev libcurl3-gnutls"
@@ -122,6 +122,7 @@ set_global_conf()
  CLAMAV_URL="http://downloads.sourceforge.net/project/clamav/clamav/${CLAMAV_VERSION}/clamav-${CLAMAV_VERSION}.tar.gz"
  CLAMSMTP_URL="http://thewalter.net/stef/software/clamsmtp/clamsmtp-${CLAMSMTP_VERSION}.tar.gz"
  PAM_MYSQL_URL="http://downloads.sourceforge.net/project/pam-mysql/pam-mysql/${PAM_MYSQL_VERSION}/pam_mysql-${PAM_MYSQL_VERSION}.tar.gz"
+ PHPMYADMIN_URL="http://downloads.sourceforge.net/project/phpmyadmin/phpMyAdmin/${PHPMYADMIN_VERSION}/phpMyAdmin-${PHPMYADMIN_VERSION}-all-languages.tar.gz"
 
  if [[ -z "$MAKEJOBS" ]] || [[ $MAKEJOBS -eq 0 ]]; then
     MAKEJOBS="$(grep -wc MHz /proc/cpuinfo 2>/dev/null)"
@@ -154,7 +155,8 @@ set_global_conf()
  SPF_VERSION \
  CLAMAV_VERSION \
  CLAMSMTP_VERSION \
- PAM_MYSQL_VERSION
+ PAM_MYSQL_VERSION \
+ PHPMYADMIN_VERSION
  export \
  MYSQL_URL \
  NGINX_URL \
@@ -167,7 +169,16 @@ set_global_conf()
  SPF_URL \
  CLAMAV_URL \
  CLAMSMTP_URL \
- PAM_MYSQL_URL
+ PAM_MYSQL_URL \
+ PHPMYADMIN_URL
+}
+
+# generate random string, need it for phpmyadmin
+generate_random()
+{
+ [ "$2" == "0" ] && CHAR="[:alnum:]" || CHAR="[:graph:]"
+ cat /dev/urandom | tr -cd "$CHAR" | head -c ${1:-32}
+ echo
 }
 
 # check if we are running Debian or Ubuntu or some derivate.
@@ -746,7 +757,7 @@ need_mysql()
 
  export buildall=1
  if [ ! -x ${PREFIX}/mysql/bin/mysql_config ]; then
-   msg info "MySQL is not installed, we need it before building ${name}"
+   msg info "MySQL is not installed, we need it before building ${name}."
    trigger mysql
  fi
  export buildall=$localall
@@ -760,8 +771,22 @@ need_php()
 
  export buildall=1
  if [ ! -x ${PREFIX}/php/bin/phpize ]; then
-   msg info "PHP is not available, we need it before building ${name}"
+   msg info "PHP is not available, we need it before building ${name}."
    trigger php
+ fi
+ export buildall=$localall
+}
+
+# trigger build of nginx, some packages need this
+need_nginx()
+{
+ local name=$1
+ local localall=$buildall
+
+ export buildall=1
+ if [ ! -x ${PREFIX}/nginx/sbin/nginx ]; then
+   msg info "nginx is not available, we need it before building ${name}."
+   trigger nginx
  fi
  export buildall=$localall
 }
@@ -1672,6 +1697,94 @@ build_spf()
  cd $CWD
 }
 
+# build and install phpmyadmin
+build_phpmyadmin()
+{
+ local name="phpmyadmin"
+ local version="${PHPMYADMIN_VERSION}"
+ local tarball="phpMyAdmin-${version}-all-languages.tar.gz"
+ local dir="phpMyAdmin-${version}-all-languages"
+ local url="${PHPMYADMIN_URL}"
+ local uid=$(id -u)
+ local cmd=
+
+ if [ $uid -ne 0 ]; then
+    cmd="sudo"
+ fi
+
+ [ -d build ] || mkdir -p build
+ cd build
+ [ -d ${dir} ] && rm -fr ${dir} || :
+
+ # we need to make sure mysql is already installed.
+ need_mysql ${name}
+
+ # we need to make sure php is already installed.
+ need_php ${name}
+
+ # we need to make sure nginx is already installed.
+ need_nginx ${name}
+
+ get_pkg ${url} ${tarball}
+ unpack_source ${tarball}
+ chown_dir ${dir}
+ cd ${dir} >/dev/null 2>&1 || { msg error "Failed to change directory."; exit 1; }
+
+ mkdir_as_root ${PREFIX}/${name}
+ $cmd cp -aRf * ${PREFIX}/${name}
+
+ stop_service nginx
+
+ if [ -e ${PREFIX}/nginx/conf/nginx.conf ]; then
+  if [ ! -e ${PREFIX}/nginx/conf/sites.d/${name}.conf ]; then
+     mkdir_as_root ${PREFIX}/nginx/conf/sites.d
+     msg info "Copying new configuration file for nginx (${name}.conf) ..."
+     cp_as_root $CWD/config.d/nginx.${name}.conf ${PREFIX}/nginx/conf/sites.d/${name}.conf
+     [ -e ${PREFIX}/nginx/conf/sites.d/${name}.conf ] && \
+     $cmd sed -i \
+       -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
+       -e "s|@@DATA@@|${DATA}/www|g" \
+       ${PREFIX}/nginx/conf/sites.d/${name}.conf >/dev/null 2>&1
+     chown_as_root root root ${PREFIX}/nginx/conf/sites.d/${name}.conf
+  fi
+ fi
+
+ if [ ! -e ${PREFIX}/${name}/config.inc.php ]; then
+    msg info "Generating a default configuration for ${name} (${PREFIX}/${name}/config.inc.php) ..."
+    $cmd cat << EOF > ${PREFIX}/${name}/config.inc.php
+/* Generated by buildpkg */
+
+$cfg['blowfish_secret'] = '$(generate_random 45)';
+
+/*
+ * Servers configuration
+ */
+$i = 0;
+
+/*
+ * First server
+ */
+$i++;
+/* Authentication type */
+$cfg['Servers'][$i]['auth_type'] = 'cookie';
+/* Server parameters */
+$cfg['Servers'][$i]['host'] = 'localhost';
+$cfg['Servers'][$i]['connect_type'] = 'tcp';
+$cfg['Servers'][$i]['compress'] = true;
+/* Select mysql if your server does not have mysqli */
+$cfg['Servers'][$i]['extension'] = 'mysqli';
+$cfg['Servers'][$i]['AllowNoPassword'] = false;
+
+EOF
+    chown_as_root root root ${PREFIX}/${name}
+ fi
+
+ start_service nginx
+
+ cd $CWD
+
+}
+
 # build and install all available packages
 build_all()
 {
@@ -1681,7 +1794,7 @@ build_all()
 
  export buildall=1
  for name in ${PACKAGES}; do
-    msg info "Building: ${name}"
+    msg info "*** Building now package: ${name}"
     build_${name}
  done
 }
@@ -1771,7 +1884,7 @@ if [ $buildpkg -eq 1 ]; then
          # we can't handle other type of distro's, yet.
          is_debian
 
-         msg info "Building now package: ${name}"
+         msg info "*** Building now package: ${name}"
          build_${name}
       fi
    fi
