phpmyadmin and awstats dont need installation blocking, they dont have one, just a warning is enough

diff --git a/buildpkg b/buildpkg
--- a/buildpkg
+++ b/buildpkg
@@ -2519,38 +2519,37 @@ build_phpmyadmin()
  chown_dir ${dir}
  cd ${dir} >/dev/null 2>&1 || { msg error "Failed to change directory."; exit 1; }
 
- if [ ${installoff} -eq 0 ]; then
-    mkdir_as_root ${wwwdir}
-    mkdir_as_root ${PREFIX}/${name}
+ mkdir_as_root ${wwwdir}
+ mkdir_as_root ${PREFIX}/${name}
 
-    ( cd ${wwwdir}
-      [ -L ${name} ] || ln_as_root ../..${PREFIX}/${name} .
-    )
+ ( cd ${wwwdir}
+   [ -L ${name} ] || ln_as_root ../..${PREFIX}/${name} .
+ )
 
-    $cmd cp -aRf * ${PREFIX}/${name}
-    for file in ChangeLog CONTRIBUTING.md DCO LICENSE README \
-               RELEASE-DATE-4.2.8 examples setup; do
-        rm_as_root ${PREFIX}/${name}/${file}
-    done
+ $cmd cp -aRf * ${PREFIX}/${name}
+ for file in ChangeLog CONTRIBUTING.md DCO LICENSE README \
+           RELEASE-DATE-4.2.8 examples setup; do
+     rm_as_root ${PREFIX}/${name}/${file}
+ done
 
-    if [ -e ${PREFIX}/nginx/conf/nginx.conf ]; then
-       if [ ! -e ${PREFIX}/nginx/conf/sites.d/${name}.conf ]; then
-          mkdir_as_root ${PREFIX}/nginx/conf/sites.d
-          msg info "Copying new configuration file for nginx (${name}.conf) ..."
-          cp_as_root $CWD/config.d/nginx.${name}.conf ${PREFIX}/nginx/conf/sites.d/${name}.conf
-          [ -e ${PREFIX}/nginx/conf/sites.d/${name}.conf ] && \
-          $cmd sed -i \
-             -e "s|@@PREFIX@@|${PREFIX}/nginx|g" \
-             -e "s|@@DATA@@|${DATA}/www/${name}|g" \
-             -e "s|@@TMPSRV@@|${TMPSRV}|g" \
-             ${PREFIX}/nginx/conf/sites.d/${name}.conf >/dev/null 2>&1
-          chown_as_root root root ${PREFIX}/nginx/conf/sites.d/${name}.conf
-       fi
+ if [ -e ${PREFIX}/nginx/conf/nginx.conf ]; then
+    if [ ! -e ${PREFIX}/nginx/conf/sites.d/${name}.conf ]; then
+       mkdir_as_root ${PREFIX}/nginx/conf/sites.d
+       msg info "Copying new configuration file for nginx (${name}.conf) ..."
+       cp_as_root $CWD/config.d/nginx.${name}.conf ${PREFIX}/nginx/conf/sites.d/${name}.conf
+       [ -e ${PREFIX}/nginx/conf/sites.d/${name}.conf ] && \
+       $cmd sed -i \
+          -e "s|@@PREFIX@@|${PREFIX}/nginx|g" \
+          -e "s|@@DATA@@|${DATA}/www/${name}|g" \
+          -e "s|@@TMPSRV@@|${TMPSRV}|g" \
+          ${PREFIX}/nginx/conf/sites.d/${name}.conf >/dev/null 2>&1
+       chown_as_root root root ${PREFIX}/nginx/conf/sites.d/${name}.conf
     fi
+ fi
 
-    if [ ! -e ${PREFIX}/${name}/config.inc.php ]; then
-       msg info "Generating a default configuration for ${name} (${PREFIX}/${name}/config.inc.php) ..."
-       $cmd cat << EOF > ${PREFIX}/${name}/config.inc.php
+ if [ ! -e ${PREFIX}/${name}/config.inc.php ]; then
+    msg info "Generating a default configuration for ${name} (${PREFIX}/${name}/config.inc.php) ..."
+    $cmd cat << EOF > ${PREFIX}/${name}/config.inc.php
 <?php
 /* Generated by buildpkg */
 
@@ -2580,17 +2579,15 @@ build_phpmyadmin()
 
 ?>
 EOF
-       chown_as_root root root ${PREFIX}/${name}
-    fi
+    chown_as_root root root ${PREFIX}/${name}
+ fi
 
-    if ! $(update_pkg_version "$name" "$version"); then
-        msg error "Failed to update $name version file."
-        exit 1
-    fi
+ if ! $(update_pkg_version "$name" "$version"); then
+    msg error "Failed to update $name version file."
+    exit 1
  fi
 
  cd $CWD
-
 }
 
 # build and install awstats
@@ -2624,87 +2621,85 @@ build_awstats()
  chown_dir ${dir}
  cd ${dir} >/dev/null 2>&1 || { msg error "Failed to change directory."; exit 1; }
 
- if [ ${installoff} -eq 0 ]; then
-    mkdir_as_root ${PREFIX}/${name}/conf 0755
-    mkdir_as_root ${PREFIX}/${name}/bin 0755
-    mkdir_as_root ${wwwdir} 0755
-    mkdir_as_root ${wwwdata} 0755
+ mkdir_as_root ${PREFIX}/${name}/conf 0755
+ mkdir_as_root ${PREFIX}/${name}/bin 0755
+ mkdir_as_root ${wwwdir} 0755
+ mkdir_as_root ${wwwdata} 0755
 
-    $cmd cp -aRf wwwroot ${PREFIX}/${name}/
-    $cmd cp -aRf tools ${PREFIX}/${name}/
-    $cmd cp -aRf docs ${PREFIX}/${name}/
-    $cmd find ${PREFIX}/${name} -type f -exec chmod 0644 {} \;
-    $cmd find ${PREFIX}/${name} -type d -exec chmod 0755 {} \;
-    chmod_as_root 0755 "${PREFIX}/${name}/wwwroot/cgi-bin/*.pl"
-    chown_as_root root root ${PREFIX}/${name}
-    chown_as_root www root ${wwwdata}
-    cp_as_root wwwroot/cgi-bin/${name}.model.conf ${PREFIX}/${name}/conf/${name}.model.conf
+ $cmd cp -aRf wwwroot ${PREFIX}/${name}/
+ $cmd cp -aRf tools ${PREFIX}/${name}/
+ $cmd cp -aRf docs ${PREFIX}/${name}/
+ $cmd find ${PREFIX}/${name} -type f -exec chmod 0644 {} \;
+ $cmd find ${PREFIX}/${name} -type d -exec chmod 0755 {} \;
+ chmod_as_root 0755 "${PREFIX}/${name}/wwwroot/cgi-bin/*.pl"
+ chown_as_root root root ${PREFIX}/${name}
+ chown_as_root www root ${wwwdata}
+ cp_as_root wwwroot/cgi-bin/${name}.model.conf ${PREFIX}/${name}/conf/${name}.model.conf
 
-    ( cd ${wwwdir}
-      [ -L ${name} ] || ln_as_root ../..${PREFIX}/${name}/wwwroot ${name}
-    )
+ ( cd ${wwwdir}
+   [ -L ${name} ] || ln_as_root ../..${PREFIX}/${name}/wwwroot ${name}
+ )
 
-    rm_as_root ${PREFIX}/${name}/wwwroot/cgi-bin/awstats.model.conf
+ rm_as_root ${PREFIX}/${name}/wwwroot/cgi-bin/awstats.model.conf
 
-    [ -e ${PREFIX}/${name}/wwwroot/cgi-bin/${name}.pl ] && \
+ [ -e ${PREFIX}/${name}/wwwroot/cgi-bin/${name}.pl ] && \
+ $cmd sed -i \
+     -e "s|/usr/local/etc/awstats|${PREFIX}/${name}/conf|g" \
+     ${PREFIX}/${name}/wwwroot/cgi-bin/${name}.pl
+
+ if [ ! -x ${PREFIX}/${name}/bin/create-awstats-config.sh ]; then
+    msg info "Copying config generator script for ${name} (create-awstats-config.sh) ..."
+    cp_as_root $CWD/scripts/create-awstats-config.sh ${PREFIX}/${name}/bin/create-awstats-config.sh
+    chown_as_root root root ${PREFIX}/${name}/bin/create-awstats-config.sh
+    chmod_as_root 0755 ${PREFIX}/${name}/bin/create-awstats-config.sh
+    [ -e ${PREFIX}/${name}/bin/create-awstats-config.sh ] && \
     $cmd sed -i \
-        -e "s|/usr/local/etc/awstats|${PREFIX}/${name}/conf|g" \
-        ${PREFIX}/${name}/wwwroot/cgi-bin/${name}.pl
+       -e "s|@@DATA@@|${wwwdata}|g" \
+       -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
+       ${PREFIX}/${name}/bin/create-awstats-config.sh
+ fi
 
-    if [ ! -x ${PREFIX}/${name}/bin/create-awstats-config.sh ]; then
-       msg info "Copying config generator script for ${name} (create-awstats-config.sh) ..."
-       cp_as_root $CWD/scripts/create-awstats-config.sh ${PREFIX}/${name}/bin/create-awstats-config.sh
-       chown_as_root root root ${PREFIX}/${name}/bin/create-awstats-config.sh
-       chmod_as_root 0755 ${PREFIX}/${name}/bin/create-awstats-config.sh
-       [ -e ${PREFIX}/${name}/bin/create-awstats-config.sh ] && \
+ if [ ! -x ${PREFIX}/${name}/bin/update-awstats.sh ]; then
+    msg info "Copying statistics generator script for ${name} (update-awstats.sh) ..."
+    cp_as_root $CWD/scripts/update-awstats.sh ${PREFIX}/${name}/bin/update-awstats.sh
+    chown_as_root root root ${PREFIX}/${name}/bin/update-awstats.sh
+    chmod_as_root 0755 ${PREFIX}/${name}/bin/update-awstats.sh
+    [ -e ${PREFIX}/${name}/bin/update-awstats.sh ] && \
+    $cmd sed -i \
+       -e "s|@@DATA@@|${wwwdata}|g" \
+       -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
+       ${PREFIX}/${name}/bin/update-awstats.sh
+ fi
+
+ if [ -e ${PREFIX}/nginx/conf/nginx.conf ]; then
+    if [ ! -e ${PREFIX}/nginx/conf/sites.d/${name}.conf ]; then
+       mkdir_as_root ${PREFIX}/nginx/conf/sites.d
+       msg info "Copying new configuration file for nginx (${name}.conf) ..."
+       cp_as_root $CWD/config.d/nginx.${name}.conf ${PREFIX}/nginx/conf/sites.d/${name}.conf
+       [ -e ${PREFIX}/nginx/conf/sites.d/${name}.conf ] && \
        $cmd sed -i \
-          -e "s|@@DATA@@|${wwwdata}|g" \
-          -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
-          ${PREFIX}/${name}/bin/create-awstats-config.sh
+          -e "s|@@DATA@@|${DATA}/www/${name}|g" \
+          -e "s|@@TMPSRV@@|${TMPSRV}|g" \
+          ${PREFIX}/nginx/conf/sites.d/${name}.conf >/dev/null 2>&1
+       chown_as_root root root ${PREFIX}/nginx/conf/sites.d/${name}.conf
     fi
+ fi
 
-    if [ ! -x ${PREFIX}/${name}/bin/update-awstats.sh ]; then
-       msg info "Copying statistics generator script for ${name} (update-awstats.sh) ..."
-       cp_as_root $CWD/scripts/update-awstats.sh ${PREFIX}/${name}/bin/update-awstats.sh
-       chown_as_root root root ${PREFIX}/${name}/bin/update-awstats.sh
-       chmod_as_root 0755 ${PREFIX}/${name}/bin/update-awstats.sh
-       [ -e ${PREFIX}/${name}/bin/update-awstats.sh ] && \
-       $cmd sed -i \
-          -e "s|@@DATA@@|${wwwdata}|g" \
-          -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
-          ${PREFIX}/${name}/bin/update-awstats.sh
-    fi
+ [ -d /etc/profile.d ] || mkdir_as_root /etc/profile.d 0755
+ if [ ! -e /etc/profile.d/${name}.sh ]; then
+    msg info "Copying ${name}.sh to /etc/profile.d ... "
+    cp_as_root $CWD/profile.d/${name}.sh /etc/profile.d
+    chown_as_root root root /etc/profile.d/${name}.sh
+    chmod_as_root 0644 /etc/profile.d/${name}.sh
+    [ -e /etc/profile.d/${name}.sh ] && \
+    $cmd sed -i \
+        -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
+        /etc/profile.d/${name}.sh >/dev/null 2>&1
+ fi
 
-    if [ -e ${PREFIX}/nginx/conf/nginx.conf ]; then
-       if [ ! -e ${PREFIX}/nginx/conf/sites.d/${name}.conf ]; then
-          mkdir_as_root ${PREFIX}/nginx/conf/sites.d
-          msg info "Copying new configuration file for nginx (${name}.conf) ..."
-          cp_as_root $CWD/config.d/nginx.${name}.conf ${PREFIX}/nginx/conf/sites.d/${name}.conf
-          [ -e ${PREFIX}/nginx/conf/sites.d/${name}.conf ] && \
-          $cmd sed -i \
-             -e "s|@@DATA@@|${DATA}/www/${name}|g" \
-             -e "s|@@TMPSRV@@|${TMPSRV}|g" \
-             ${PREFIX}/nginx/conf/sites.d/${name}.conf >/dev/null 2>&1
-           chown_as_root root root ${PREFIX}/nginx/conf/sites.d/${name}.conf
-       fi
-    fi
-
-    [ -d /etc/profile.d ] || mkdir_as_root /etc/profile.d 0755
-    if [ ! -e /etc/profile.d/${name}.sh ]; then
-       msg info "Copying ${name}.sh to /etc/profile.d ... "
-       cp_as_root $CWD/profile.d/${name}.sh /etc/profile.d
-       chown_as_root root root /etc/profile.d/${name}.sh
-       chmod_as_root 0644 /etc/profile.d/${name}.sh
-       [ -e /etc/profile.d/${name}.sh ] && \
-       $cmd sed -i \
-           -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
-           /etc/profile.d/${name}.sh >/dev/null 2>&1
-    fi
-
-    if ! $(update_pkg_version "$name" "$version"); then
-       msg error "Failed to update $name version file."
-       exit 1
-    fi
+ if ! $(update_pkg_version "$name" "$version"); then
+    msg error "Failed to update $name version file."
+    exit 1
  fi
 
  cd $CWD
