build_postfix, build_spf and build_greyfix work properly, everything works out of the box :)

diff --git a/buildpkg b/buildpkg
--- a/buildpkg
+++ b/buildpkg
@@ -20,7 +20,7 @@ monitdeps="build-essential intltool libssl-dev libpam0g-dev libbz2-dev zlib1g-de
 postfixdeps="build-essential intltool libdb-dev libsasl2-dev libsqlite3-dev libbz2-dev zlib1g-dev libssl-dev libpcre3-dev patch"
 greyfixdeps="build-essential intltool libdb-dev zlib1g-dev"
 dovecotdeps="build-essential intltool libtool libdb-dev libldap2-dev libsasl2-dev libsqlite3-dev pkg-config libbz2-dev zlib1g-dev libssl-dev"
-spfdeps="perl libmail-sendmail-perl libsys-hostname-long-perl"
+spfdeps="perl libmail-sendmail-perl libsys-hostname-long-perl libmail-spf-perl"
 clamavdeps="build-essential libgcc1 intltool libtool libltdl7 libmail-sendmail-perl libmilter-dev libmilter1.0.1 libsys-hostname-long-perl libtommath-dev libtommath0 zlib1g-dev libbz2-dev"
 clamsmtpdeps="build-essential libmail-sendmail-perl libsys-hostname-long-perl"
 
@@ -31,7 +31,7 @@ export triggeroff=0
 usage()
 {
  cat << EOF
-${name} script $VERSION
+${NAME} script ${VERSION}
 Report bugs at <robert@linux-source.org>
 
 Usage: ${name} [options...]
@@ -48,7 +48,7 @@ Usage: ${name} [options...]
     ${name} --all (build all packages available)
 
   AVAILABLE PACKAGES:
-    $PACKAGES
+    ${PACKAGES}
 
 EOF
 }
@@ -66,7 +66,7 @@ msg()
    error)
     echo "${NAME}: error: $message" ;;
    *)
-    echo '${NAME}: missing arguments, usage: "error some message"' ;;
+    echo "${NAME}: msg(): missing arguments, usage: \"msg info some_message\"" ;;
  esac
 }
 
@@ -477,30 +477,33 @@ chown_as_root()
 {
  local user=$1
  local group=$2
- local dir=$3
+ local source=$3
  local uid=$(id -u)
- local cmd="chown ${user}.${group} -R ${dir}"
+ local cmd="chown ${user}.${group} ${source}"
 
  if [ $uid -ne 0 ]; then
     cmd="sudo ${cmd}"
  fi
+ if [ $(file ${source} |grep -qw directory >/dev/null 2>&1; echo $?) -eq 0 ]; then
+    cmd="${cmd} -R"
+ fi
 
- $cmd >/dev/null 2>&1 || msg error "Failed to change ownership on ${dir} to ${user}.${group}."
+ $cmd >/dev/null 2>&1 || msg error "Failed to change ownership on ${source} to ${user}.${group}."
 }
 
 # change rights as root
 chmod_as_root()
 {
  local mode=$1
- local dir=$2
+ local source=$2
  local uid=$(id -u)
- local cmd="chmod ${mode} ${dir}"
+ local cmd="chmod ${mode} ${source}"
 
  if [ $uid -ne 0 ]; then
     cmd="sudo ${cmd}"
  fi
 
- $cmd >/dev/null 2>&1 || msg error "Failed to change rights on ${dir}."
+ $cmd >/dev/null 2>&1 || msg error "Failed to change rights on ${source}."
 }
 
 # create directories as root
@@ -840,18 +843,18 @@ build_mysql()
       -e "s|@@TMPSRV@@|${TMPSRV}|g" \
       -e "s|@@MYDB@@|${MYDB}|g" \
       -e "s|@@MYLOG@@|${MYDB}|g" \
-      ${PREFIX}/${name}/conf/my.cnf
+      ${PREFIX}/${name}/conf/my.cnf >/dev/null 2>&1
  fi
- if [ ! -e /etc/init.d/mysql ]; then
-    msg info "Copying start/stop script for ${name} (/etc/init.d/mysql) ..."
-    cp_as_root $CWD/scripts/mysql /etc/init.d/mysql
-    chown_as_root root root /etc/init.d/mysql
-    chmod_as_root 0755 /etc/init.d/mysql
-    [ -e /etc/init.d/mysql ] && \
+ if [ ! -e /etc/init.d/${name} ]; then
+    msg info "Copying start/stop script for ${name} (/etc/init.d/${name}) ..."
+    cp_as_root $CWD/scripts/${name} /etc/init.d/${name}
+    chown_as_root root root /etc/init.d/${name}
+    chmod_as_root 0755 /etc/init.d/${name}
+    [ -e /etc/init.d/${name} ] && \
     $cmd sed -i \
       -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
       -e "s|@@MYDB@@|${MYDB}|g" \
-      /etc/init.d/mysql
+      /etc/init.d/${name} >/dev/null 2>&1
  fi
 
  if [ ! -e ${dbdir}/mysql/db.frm ]; then
@@ -889,6 +892,12 @@ build_nginx()
  local url="${NGINX_URL}"
  local wwwlog=/var/log/${name}
  local wwwdir=${DATA}/www
+ local uid=$(id -u)
+ local cmd=
+
+ if [ $uid -ne 0 ]; then
+    cmd="sudo"
+ fi
 
  [ -d build ] || mkdir -p build
  cd build
@@ -932,6 +941,52 @@ build_nginx()
 
  mkdir_as_root ${wwwdir} 0755
  chown_as_root www root ${wwwdir}
+
+ if [ ! -e ${PREFIX}/${name}/conf/.do-not-delete-me ]; then
+    mkdir_as_root ${PREFIX}/${name}/conf/sites.d
+    mkdir_as_root ${DATA}/www/${HOST}
+    [ -e ${PREFIX}/${name}/conf/${name}.conf ] && rm_as_root ${PREFIX}/${name}/conf/${name}.conf
+    msg info "Copying new configuration file for ${name} (${name}.conf) ..."
+    cp_as_root $CWD/config.d/${name}.conf ${PREFIX}/${name}/conf/${name}.conf
+    [ -e ${PREFIX}/${name}/conf/fastcgi.conf ] && rm_as_root ${PREFIX}/${name}/conf/fastcgi.conf
+    msg info "Copying new configuration file for ${name} (fastcgi.conf) ..."
+    cp_as_root $CWD/config.d/fastcgi.conf ${PREFIX}/${name}/conf/fastcgi.conf
+    [ -e ${PREFIX}/${name}/conf/proxy.conf ] && rm_as_root ${PREFIX}/${name}/conf/proxy.conf
+    msg info "Copying new configuration file for ${name} (proxy.conf) ..."
+    cp_as_root $CWD/config.d/proxy.conf ${PREFIX}/${name}/conf/proxy.conf
+    [ -e ${PREFIX}/${name}/conf/sites.d/${HOST}.conf ] && rm_as_root ${PREFIX}/${name}/conf/sites.d/${HOST}.conf
+    msg info "Copying new configuration file for ${name} (${HOST}.conf) ..."
+    cp_as_root $CWD/config.d/${name}.example.conf ${PREFIX}/${name}/conf/sites.d/${HOST}.conf
+    [ -e ${PREFIX}/${name}/conf/${name}.conf ] && \
+    $cmd sed -i \
+      -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
+      ${PREFIX}/${name}/conf/${name}.conf >/dev/null 2>&1
+    [ -e ${PREFIX}/${name}/conf/sites.d/${HOST}.conf ] && \
+    $cmd sed -i \
+      -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
+      -e "s|@@HOST@@|${HOST}|g" \
+      -e "s|@@DATA@@|${DATA}/www/${HOST}|g" \
+      ${PREFIX}/${name}/conf/sites.d/${HOST}.conf >/dev/null 2>&1
+    msg info "Copying PHP example file for ${name} (index.php) ..."
+    cp_as_root $CWD/config.d/nginx-test-pages/index.php ${DATA}/www/${HOST}/index.php
+    msg info "Copying HTML example file for ${name} (index.htm) ..."
+    cp_as_root $CWD/config.d/nginx-test-pages/index.htm ${DATA}/www/${HOST}/index.htm
+    $cmd touch ${PREFIX}/${name}/conf/.do-not-delete-me
+    chown_as_root root root ${DATA}/www/${HOST}
+    chown_as_root root root ${PREFIX}/${name}/conf
+ fi
+
+ if [ ! -e /etc/init.d/${name} ]; then
+    msg info "Copying start/stop script for ${name} (/etc/init.d/${name}) ..."
+    cp_as_root $CWD/scripts/${name} /etc/init.d/${name}
+    chown_as_root root root /etc/init.d/${name}
+    chmod_as_root 0755 /etc/init.d/${name}
+    [ -e /etc/init.d/${name} ] && \
+    $cmd sed -i \
+      -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
+      -e "s|@@TMPSRV@@|${TMPSRV}/${name}|g" \
+      /etc/init.d/${name} >/dev/null 2>&1
+ fi
 
  start_service ${name}
 
@@ -1019,8 +1074,8 @@ build_php()
  run_make ${name}
  strip_dir ${PREFIX}/${name}
 
- mkdir_as_root /var/log/nginx 0770
- chown_as_root www root /var/log/nginx
+ mkdir_as_root /var/log/${name} 0770
+ chown_as_root www root /var/log/${name}
 
  [ -d ${PREFIX}/${name}/conf ] || mkdir_as_root ${PREFIX}/${name}/conf
  if [ ! -e ${PREFIX}/${name}/conf/${name}.ini ]; then
@@ -1030,17 +1085,20 @@ build_php()
     [ -e ${PREFIX}/${name}/conf/${name}.ini ] && \
     $cmd sed -i \
       -e "s|@@TMPSRV@@|${TMPSRV}|g" \
-      ${PREFIX}/${name}/conf/${name}.ini
+      ${PREFIX}/${name}/conf/${name}.ini >/dev/null 2>&1
  fi
- if [ ! -e ${PREFIX}/${name}/conf/${name}-fpm.conf ]; then
+ if [ ! -e ${PREFIX}/${name}/conf/.do-not-delete-me ]; then
     msg info "Copying new configuration file for ${name} (${name}-fpm.conf) ..."
+    [ -e ${PREFIX}/${name}/conf/${name}-fpm.conf ] && rm_as_root ${PREFIX}/${name}/conf/${name}-fpm.conf
     cp_as_root $CWD/config.d/${name}-fpm.conf ${PREFIX}/${name}/conf/${name}-fpm.conf
-    chown_as_root root root ${PREFIX}/${name}/conf
     [ -e ${PREFIX}/${name}/conf/${name}-fpm.conf ] && \
     $cmd sed -i \
       -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
-      ${PREFIX}/${name}/conf/${name}-fpm.conf
+      ${PREFIX}/${name}/conf/${name}-fpm.conf >/dev/null 2>&1
+    $cmd touch ${PREFIX}/${name}/conf/.do-not-delete-me
+    chown_as_root root root ${PREFIX}/${name}/conf
  fi
+
  if [ ! -e /etc/init.d/${name}-fpm ]; then
     msg info "Copying start/stop script for ${name} (/etc/init.d/${name}-fpm) ..."
     cp_as_root $CWD/scripts/${name}-fpm /etc/init.d/${name}-fpm
@@ -1050,7 +1108,7 @@ build_php()
     $cmd sed -i \
       -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
       -e "s|@@TMPSRV@@|${TMPSRV}|g" \
-      /etc/init.d/${name}-fpm
+      /etc/init.d/${name}-fpm >/dev/null 2>&1
  fi
 
  start_service ${name}-fpm
@@ -1146,7 +1204,7 @@ build_eaccelerator()
     chown_as_root root root ${PREFIX}/php/conf/conf.d
     $cmd sed -i \
       -e "s|@@TMPSRV@@|${TMPSRV}|g" \
-      ${PREFIX}/php/conf/conf.d/eaccelerator.ini
+      ${PREFIX}/php/conf/conf.d/eaccelerator.ini >/dev/null 2>&1
  fi
 
  start_service php-fpm
@@ -1164,6 +1222,12 @@ build_postfix()
  local url="${POSTFIX_URL}"
  local queue="/var/spool/${name}"
  local lib="/var/lib/${name}"
+ local uid=$(id -u)
+ local cmd=
+
+ if [ $uid -ne 0 ]; then
+    cmd="sudo"
+ fi
 
  [ -d build ] || mkdir -p build
  cd build
@@ -1200,17 +1264,21 @@ build_postfix()
  for dir in active bounce corrupt defer deferred flush \
    hold incoming maildrop pid private public saved trace; do
      mkdir_as_root ${queue}/${dir}
- done
- for dir in active bounce corrupt defer deferred flush \
-   hold incoming private public maildrop trace saved; do
      chown_as_root postfix root ${queue}/${dir}
+     chmod_as_root 0700 ${queue}/${dir}
  done
- chown_as_root root postdrop ${queue}/public ${queue}/maildrop
- chown_as_root root postdrop ${PREFIX}/${name}/sbin/postqueue ${PREFIX}/${name}/sbin/postdrop
- chmod_as_root 0770 ${queue}/maildrop
- chmod_as_root g+s ${PREFIX}/${name}/sbin/postqueue ${PREFIX}/${name}/sbin/postdrop
+
+ chown_as_root root postdrop ${PREFIX}/${name}/sbin/postqueue
+ chown_as_root root postdrop ${PREFIX}/${name}/sbin/postdrop
+ chown_as_root postfix postdrop ${queue}/public
+ chown_as_root postfix postdrop ${queue}/maildrop
  chown_as_root postfix root ${lib}
- chmod_as_root 0755 ${lib}
+ chmod_as_root 2755 ${PREFIX}/${name}/sbin/postqueue
+ chmod_as_root 2755 ${PREFIX}/${name}/sbin/postdrop
+ chmod_as_root 0770 ${queue}/maildrop
+ chmod_as_root 0770 ${queue}/public
+ chmod_as_root 0755 ${queue}/pid
+ chmod_as_root 0750 ${lib}
 
  ( cd ${PREFIX}/${name}
    mv_as_root usr/sbin/sendmail sbin
@@ -1230,6 +1298,28 @@ build_postfix()
  ln_as_root ${PREFIX}/${name}/sbin/sendmail /usr/lib/sendmail
  ln_as_root ${PREFIX}/${name}/conf /etc/postfix
 
+ if [ ! -e /etc/init.d/${name} ]; then
+    msg info "Copying start/stop script for ${name} (/etc/init.d/${name}) ..."
+    cp_as_root $CWD/scripts/${name} /etc/init.d/${name}
+    chown_as_root root root /etc/init.d/${name}
+    chmod_as_root 0755 /etc/init.d/${name}
+    [ -e /etc/init.d/${name} ] && \
+    $cmd sed -i \
+      -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
+      /etc/init.d/${name} >/dev/null 2>&1
+ fi
+
+ if [ -e ${PREFIX}/${name}/conf/main.cf ]; then
+    $cmd sed -i \
+      -e "s|^command_directory.*|command_directory = ${PREFIX}/${name}/sbin|g" \
+      -e "s|^daemon_directory.*|daemon_directory = ${PREFIX}/${name}/libexec|g" \
+      -e "s|^html_directory.*|html_directory = ${PREFIX}/${name}/html|g" \
+      -e "s|^manpage_directory.*|manpage_directory = ${PREFIX}/${name}/man|g" \
+      -e "s|^sample_directory.*|sample_directory = ${PREFIX}/${name}/sample|g" \
+      -e "s|^readme_directory.*|readme_directory = ${PREFIX}/${name}/doc|g" \
+      ${PREFIX}/${name}/conf/main.cf >/dev/null 2>&1
+ fi
+
  start_service ${name}
 
  cd $CWD
@@ -1243,6 +1333,12 @@ build_greyfix()
  local tarball="${name}-${version}.tar.gz"
  local dir="${name}-${version}"
  local url="${GREYFIX_URL}"
+ local uid=$(id -u)
+ local cmd=
+
+ if [ $uid -ne 0 ]; then
+    cmd="sudo"
+ fi
 
  [ -d build ] || mkdir -p build
  cd build
@@ -1264,6 +1360,18 @@ build_greyfix()
  mkdir_as_root /var/lib/${name}
  chown_as_root nobody root /var/lib/${name}
  chmod_as_root 0750 /var/lib/${name}
+
+ if [ ! -e ${PREFIX}/${name}/sbin/autogrey ]; then
+    msg info "Copying postfix integration script for ${name} (${PREFIX}/${name}/sbin/autogrey) ..."
+    cp_as_root $CWD/scripts/autogrey ${PREFIX}/${name}/sbin/autogrey
+    chown_as_root root root ${PREFIX}/${name}/sbin/autogrey
+    chmod_as_root 0755 ${PREFIX}/${name}/sbin/autogrey
+    [ -e ${PREFIX}/${name}/sbin/autogrey ] && \
+    $cmd sed -i \
+      -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
+      -e "s|@@HOST@@|${HOST}|g" \
+      ${PREFIX}/${name}/sbin/autogrey >/dev/null 2>&1
+ fi
 
  cd $CWD
 }
@@ -1384,25 +1492,25 @@ build_clamav()
 
  if [ $(grep -qw ^Example ${PREFIX}/${name}/conf/clamd.conf 2>/dev/null; echo $?) -eq 0 ]; then
     msg info "Copying new configuration file for ${name} (clamd.conf) ..."
-    rm -f ${PREFIX}/${name}/conf/clamd.conf >/dev/null 2>&1
+    [ -e ${PREFIX}/${name}/conf/clamd.conf ] && rm_as_root ${PREFIX}/${name}/conf/clamd.conf
     cp_as_root $CWD/config.d/clamd.conf ${PREFIX}/${name}/conf
     chown_as_root root root ${PREFIX}/${name}/conf
     [ -e ${PREFIX}/${name}/conf/clamd.conf ] && \
     $cmd sed -i \
       -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
       -e "s|@@TMPSRV@@|${TMPSRV}|g" \
-      ${PREFIX}/${name}/conf/clamd.conf
+      ${PREFIX}/${name}/conf/clamd.conf >/dev/null 2>&1
  fi
  if [ $(grep -qw ^Example ${PREFIX}/${name}/conf/freshclam.conf 2>/dev/null; echo $?) -eq 0 ]; then
     msg info "Copying new configuration file for ${name} (freshclam.conf) ..."
-    rm -f ${PREFIX}/${name}/conf/freshclam.conf >/dev/null 2>&1
+    [ -e ${PREFIX}/${name}/conf/freshclam.conf ] && rm_as_root ${PREFIX}/${name}/conf/freshclam.conf
     cp_as_root $CWD/config.d/freshclam.conf ${PREFIX}/${name}/conf
     chown_as_root root root ${PREFIX}/${name}/conf
     [ -e ${PREFIX}/${name}/conf/freshclam.conf ] && \
     $cmd sed -i \
       -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
       -e "s|@@TMPSRV@@|${TMPSRV}|g" \
-      ${PREFIX}/${name}/conf/freshclam.conf
+      ${PREFIX}/${name}/conf/freshclam.conf >/dev/null 2>&1
  fi
 
  if [ ! -e /etc/init.d/${name}-clamd ]; then
@@ -1413,7 +1521,7 @@ build_clamav()
     [ -e /etc/init.d/${name}-clamd ] && \
     $cmd sed -i \
       -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
-      /etc/init.d/${name}-clamd
+      /etc/init.d/${name}-clamd >/dev/null 2>&1
  fi
  if [ ! -e /etc/init.d/${name}-freshclam ]; then
     msg info "Copying start/stop script for ${name} (/etc/init.d/${name}-freshclam) ..."
@@ -1423,7 +1531,7 @@ build_clamav()
     [ -e /etc/init.d/${name}-freshclam ] && \
     $cmd sed -i \
       -e "s|@@PREFIX@@|${PREFIX}/${name}|g" \
-      /etc/init.d/${name}-freshclam
+      /etc/init.d/${name}-freshclam >/dev/null 2>&1
  fi
 
  if [ -d /var/lib/${name} ]; then
@@ -1528,10 +1636,10 @@ build_spf()
  cd ${dir} >/dev/null 2>&1 || { msg error "Failed to change directory."; exit 1; }
 
  mkdir_as_root ${PREFIX}/postfix/scripts
- msg info "Install ${name} in ${PREFIX}/postfix/scripts ..."
- install -m755 postfix-policyd-spf-perl \
-   ${PREFIX}/postfix/scripts >/dev/null 2>&1 || { msg error "Failed to install ${name}."; exit1; }
- get_package libmail-spf-perl
+ msg info "Installing ${name} script in ${PREFIX}/postfix/scripts ..."
+ cp_as_root postfix-policyd-spf-perl \
+   ${PREFIX}/postfix/scripts >/dev/null 2>&1
+ chmod_as_root 0755 ${PREFIX}/postfix/scripts/postfix-policyd-spf-perl
 
  cd $CWD
 }
@@ -1544,7 +1652,7 @@ build_all()
  is_debian
 
  export buildall=1
- for name in $PACKAGES; do
+ for name in ${PACKAGES}; do
     msg info "Building: ${name}"
     build_${name}
  done
@@ -1604,7 +1712,7 @@ while [ $# -gt 0 ]; do
   ;;
 
   --all)
-     msg warn "Building all available packages: $(echo $PACKAGES | sed 's/ /, /g')"
+     msg warn "Building all available packages: $(echo ${PACKAGES} | sed 's/ /, /g')"
      msg warn "This option will build all packages and it can take up to several hours to finish depending on the speed of your computer."
      msg warn "If you are not sure what you are doing, just press now Ctrl+C to stop or Enter to continue with package build."
      read
@@ -1625,7 +1733,7 @@ if [ $buildpkg -eq 1 ]; then
       msg error "missing package name."
       exit 1
    else
-      pkg=$(echo $PACKAGES | grep -w ${name} 2>/dev/null)
+      pkg=$(echo ${PACKAGES} | grep -w ${name} 2>/dev/null)
       if [ -z "$pkg" ]; then
          usage
          msg error "${name} package is not available at this moment."
