dont fail on autoreconf, add aclocal and libtoolize for fcgiwrap

diff --git a/buildpkg b/buildpkg
--- a/buildpkg
+++ b/buildpkg
@@ -1411,16 +1411,16 @@ build_nginx()
  chown_dir ${fcginame}
  cd ${fcginame} >/dev/null 2>&1 || { msg error "Failed to change directory."; exit 1; }
 
- if [ -x /usr/bin/autoreconf ]; then
-    /usr/bin/autoreconf -i >/dev/null 2>&1
-    if [ $? -ne 0 ]; then
-       msg error "autoreconf -i failed."
-       exit 1;
-    fi
- else
-    msg error "autoreconf not found."
-    exit 1
- fi
+ [ -x /usr/bin/libtoolize ] || { msg error "libtoolize not found."; exit 1 }
+ [ -x /usr/bin/aclocal ] || { msg error "aclocal not found."; exit 1 }
+ [ -x /usr/bin/autoreconf ] || { msg error "autoreconf not found."; exit 1 }
+
+ msg info "Running /usr/bin/libtoolize ..."
+ /usr/bin/libtoolize >/dev/null 2>&1 || msg error "libtoolize failed."
+ msg info "Running /usr/bin/aclocal ..."
+ /usr/bin/aclocal >/dev/null 2>&1 || msg error "aclocal failed."
+ msg info "Running /usr/bin/autoreconf ..."
+ /usr/bin/autoreconf -i >/dev/null 2>&1 || msg error "autoreconf failed."
 
  do_configure fcgiwrap
  run_make fcgiwrap
