add a wider support for versioning, update some package versions

diff --git a/buildpkg b/buildpkg
--- a/buildpkg
+++ b/buildpkg
@@ -304,10 +304,13 @@ version_check()
 get_pkg_version()
 {
  local name="$1"
+ local location="$2"
  local version="0"
 
- if [ -r "$PREFIX/$name/.$name-version" ]; then
-    version="$(cat $PREFIX/$name/.$name-version 2>/dev/null || echo 0)"
+ [ -z "$location" ] && location="$PREFIX/$name"
+
+ if [ -r "$location/.$name-version" ]; then
+    version="$(cat $location/.$name-version 2>/dev/null || echo 0)"
  fi
 
  echo $version
@@ -318,12 +321,14 @@ update_pkg_version()
 {
  local name="$1"
  local version="$2"
+ local location="$3"
 
- [ -z $name ] && return 1
- [ -z $version ] && return 1
+ [ -z "$name" ] && return 1
+ [ -z "$version" ] && return 1
+ [ -z "$location" ] && location="$PREFIX/$name"
 
- if [ -d "$PREFIX/$name" ]; then
-    echo "$version" > "$PREFIX/$name/.$name-version" 2>/dev/null
+ if [ -d "$location" ]; then
+    echo "$version" > "$location/.$name-version" 2>/dev/null
     if [ $? -eq 0 ]; then
        return 0
     fi
@@ -336,11 +341,13 @@ update_pkg_version()
 is_pkg_installed()
 {
  local name="$1"
+ local location="$2"
 
- [ -z $name ] && return 1
+ [ -z "$name" ] && return 1
+ [ -z "$location" ] && location="$PREFIX/$name"
 
- if [ -d "$PREFIX/$name" ]; then
-    if [ -r "$PREFIX/$name/.$name-version" ]; then
+ if [ -d "$location" ]; then
+    if [ -r "$location/.$name-version" ]; then
        return 0
     fi
     return 2
@@ -1814,6 +1821,11 @@ build_php_mongo()
 
     stop_service php-fpm
     start_service php-fpm
+
+    if ! $(update_pkg_version "php_mongo" "$version" "${PREFIX}/php/modules" ); then
+        msg error "Failed to update $name version file."
+        exit 1
+    fi
  fi
 
  cd $CWD
@@ -2710,10 +2722,14 @@ check_all()
 {
  local version
  local new_version
+ local location
 
  for name in ${PACKAGES}; do
-    if $(is_pkg_installed $name); then
-       version="$(get_pkg_version $name)"
+    if [ "$name" == "php_mongo" ]; then
+       location="${PREFIX}/php/modules"
+    fi
+    if $(is_pkg_installed $name $location); then
+       version="$(get_pkg_version $name $location)"
        if [ "$version" != "0" ]; then
           msg info "package: ${COL_YELLOW}$name${COL_RESET}"
           new_version="$(echo $name | tr '[:lower:]' '[:upper:]')_VERSION"
