update most applications version, fix monit to build and install properly without any interaction from the user.

diff --git a/scripts/monit b/scripts/monit
--- a/scripts/monit
+++ b/scripts/monit
@@ -2,7 +2,7 @@
 
 ### BEGIN INIT INFO
 # Provides:          monit
-# Required-Start:    $remote_fs nginx php-fastcgi mysql clamav-clamd dovecot postfix sshd
+# Required-Start:    $remote_fs sshd
 # Required-Stop:     $remote_fs
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
@@ -11,38 +11,42 @@
 
 prefix=@@PREFIX@@
 DAEMON=${prefix}/bin/monit
-CONFIG=${prefix}/conf/monitrc
+CONFIG=${prefix}/conf/monit.conf
 ARGS="-c ${CONFIG} -s /var/run/monit/monit.state"
 NAME=monit
 DESC=monit
 
 PATH=${prefix}/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-test -f $DAEMON || exit 0
+test -f ${DAEMON} || exit 0
 set -e
 
 . /lib/lsb/init-functions
 
 monit_check_config () {
     # Check for emtpy config, probably default configfile.
-    if [ "`grep -s -v \"^#\" $CONFIG`" = "" ]; then
-        echo " empty config, please edit $CONFIG."
+    if [ "`grep -s -v \"^#\" ${CONFIG}`" = "" ]; then
+        echo " empty config, please edit ${CONFIG}."
         exit 0
     fi
 }
 
 monit_checks () {
  monit_check_config
- $DAEMON -t
- /bin/chmod go-rwx $CONFIG
  [ -d /var/run/monit ] || mkdir -p -m 0750 /var/run/monit
+ /bin/chmod go-rwx ${CONFIG}
+ ${DAEMON} -t >/dev/null 2>&1
+ if [ $? -ne 0 ]; then
+   log_failure_msg "error in ${CONFIG}, please check it and try again"
+   exit 1
+ fi
 }
 
 case "$1" in
   start)
    log_daemon_msg "Starting monit" "$DESC"
    monit_checks $1
-   start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
-          --exec $DAEMON > /dev/null 2>&1 -- $ARGS
+   start-stop-daemon --start --quiet --pidfile /var/run/${NAME}.pid \
+          --exec ${DAEMON} > /dev/null 2>&1 -- $ARGS
    if [ $? -eq 0 ]; then
       log_end_msg 0
    else
@@ -51,8 +55,8 @@ case "$1" in
   ;;
   stop)
    log_daemon_msg "Stopping monit" "$DESC"
-   start-stop-daemon --retry 5 --oknodo --stop --quiet --pidfile /var/run/$NAME.pid \
-          --exec $DAEMON  > /dev/null 2>&1
+   start-stop-daemon --retry 5 --oknodo --stop --quiet --pidfile /var/run/${NAME}.pid \
+          --exec ${DAEMON}  > /dev/null 2>&1
    if [ $? -eq 0 ]; then
       log_end_msg 0
    else
@@ -69,7 +73,7 @@ case "$1" in
    monit_check_syntax
   ;;
   *)
-   N=/etc/init.d/$NAME
+   N=/etc/init.d/${NAME}
    echo "Usage: $N {start|stop|restart|force-reload|syntax}" >&2
    exit 1
   ;;
