small fixes and clean-up for some of that start/stop scripts.

diff --git a/scripts/mysql b/scripts/mysql
--- a/scripts/mysql
+++ b/scripts/mysql
@@ -10,6 +10,7 @@
 # Description: MySQL is a very fast and reliable SQL database engine.
 ### END INIT INFO
 
+NAME=mysql
 basedir=@@PREFIX@@
 datadir=@@MYDB@@/mysql
 service_startup_timeout=900
@@ -84,17 +85,16 @@ wait_for_pid () {
 
   i=0
   avoid_race_condition="by checking again"
-
-  while test $i -ne $service_startup_timeout ; do
+  while test $i -ne ${service_startup_timeout} ; do
 
     case "$verb" in
       'created')
         # wait for a PID-file to pop into existence.
-        test -s "$pid_file_path" && i='' && break
+        test -s "${pid_file_path}" && i='' && break
         ;;
       'removed')
         # wait for this PID-file to disappear
-        test ! -s "$pid_file_path" && i='' && break
+        test ! -s "${pid_file_path}" && i='' && break
         ;;
       *)
         echo "wait_for_pid () usage: wait_for_pid created|removed pid pid_file_path"
@@ -114,15 +114,12 @@ wait_for_pid () {
         fi
 
         # there's nothing that will affect the file.
-        log_failure_msg "The server quit without updating PID file ($pid_file_path)."
+        log_failure_msg "The server quit without updating PID file (${pid_file_path})."
         return 1  # not waiting any more.
       fi
     fi
-
-    echo $echo_n ".$echo_c"
-    i=`expr $i + 1`
+    i=$(expr $i + 1)
     sleep 1
-
   done
 
   if test -z "$i" ; then
@@ -139,12 +136,12 @@ wait_for_pid () {
 if test -x ./bin/my_print_defaults
 then
   print_defaults="./bin/my_print_defaults"
-elif test -x $bindir/my_print_defaults
+elif test -x ${bindir}/my_print_defaults
 then
-  print_defaults="$bindir/my_print_defaults"
-elif test -x $bindir/mysql_print_defaults
+  print_defaults="${bindir}/my_print_defaults"
+elif test -x ${bindir}/mysql_print_defaults
 then
-  print_defaults="$bindir/mysql_print_defaults"
+  print_defaults="${bindir}/mysql_print_defaults"
 else
   # Try to find basedir in /etc/my.cnf
   conf=${basedir}/conf/my.cnf
@@ -170,7 +167,7 @@ else
   fi
 
   # Hope it's in the PATH ... but I doubt it
-  test -z "$print_defaults" && print_defaults="my_print_defaults"
+  test -z "${print_defaults}" && print_defaults="my_print_defaults"
 fi
 
 #
@@ -189,18 +186,18 @@ else
   fi
 fi
 
-parse_server_arguments `$print_defaults $extra_args mysqld server mysql_server mysql.server`
+parse_server_arguments `${print_defaults} ${extra_args} mysqld server mysql_server mysql.server`
 
 #
 # Set pid file if not given
 #
-if test -z "$mysqld_pid_file_path"
+if test -z "${mysqld_pid_file_path}"
 then
   mysqld_pid_file_path=${datadir}/`hostname`.pid
 else
-  case "$mysqld_pid_file_path" in
+  case "${mysqld_pid_file_path}" in
     /* ) ;;
-    * )  mysqld_pid_file_path="${datadir}/$mysqld_pid_file_path" ;;
+    * )  mysqld_pid_file_path="${datadir}/${mysqld_pid_file_path}" ;;
   esac
 fi
 
@@ -211,23 +208,23 @@ case "$mode" in
     # Safeguard (relative paths, core dumps..)
     cd ${basedir}
 
-    echo $echo_n "Starting MySQL"
-    if test -x $bindir/mysqld_safe
+    log_daemon_msg "Starting MySQL Server" "$NAME"
+    if test -x ${bindir}/mysqld_safe
     then
       # Give extra arguments to mysqld with the my.cnf file. This script
       # may be overwritten at next upgrade.
-      $bindir/mysqld_safe --datadir="${datadir}" --pid-file="$mysqld_pid_file_path" $other_args >/dev/null 2>&1 &
-      wait_for_pid created "$!" "$mysqld_pid_file_path"; return_value=$?
+      ${bindir}/mysqld_safe --datadir="${datadir}" --pid-file="${mysqld_pid_file_path}" ${other_args} >/dev/null 2>&1 &
+      wait_for_pid created "$!" "${mysqld_pid_file_path}"; return_value=$?
 
       # Make lock for RedHat / SuSE
       if test -w "${lockdir}"
       then
-        touch "$lock_file_path"
+        touch "${$lock_file_path}"
       fi
 
       exit $return_value
     else
-      log_failure_msg "Couldn't find MySQL server ($bindir/mysqld_safe)"
+      log_failure_msg "Couldn't find MySQL server (${bindir}/mysqld_safe)"
     fi
     ;;
 
@@ -235,25 +232,26 @@ case "$mode" in
     # Stop daemon. We use a signal here to avoid having to know the
     # root password.
 
-    if test -s "$mysqld_pid_file_path"
+    if test -s "${mysqld_pid_file_path}"
     then
-      mysqld_pid=`cat "$mysqld_pid_file_path"`
+      mysqld_pid=`cat "${mysqld_pid_file_path}"`
 
-      if (kill -0 $mysqld_pid 2>/dev/null)
+      if (kill -0 ${mysqld_pid} 2>/dev/null)
       then
         echo $echo_n "Shutting down MySQL"
-        kill $mysqld_pid
+        log_daemon_msg "Shutting down MySQL Server" "$NAME"
+        kill ${mysqld_pid}
         # mysqld should remove the pid file when it exits, so wait for it.
-        wait_for_pid removed "$mysqld_pid" "$mysqld_pid_file_path"; return_value=$?
+        wait_for_pid removed "${mysqld_pid}" "${mysqld_pid_file_path}"; return_value=$?
       else
-        log_failure_msg "MySQL server process #$mysqld_pid is not running!"
-        rm "$mysqld_pid_file_path"
+        log_failure_msg "MySQL server process #${mysqld_pid} is not running!"
+        rm "${mysqld_pid_file_path}"
       fi
 
       # Delete lock for RedHat / SuSE
-      if test -f "$lock_file_path"
+      if test -f "${$lock_file_path}"
       then
-        rm -f "$lock_file_path"
+        rm -f "${$lock_file_path}"
       fi
       exit $return_value
     else
@@ -264,8 +262,8 @@ case "$mode" in
   'restart')
     # Stop the service and regardless of whether it was
     # running or not, start it again.
-    if $0 stop  $other_args; then
-      $0 start $other_args
+    if $0 stop  ${other_args}; then
+      $0 start ${other_args}
     else
       log_failure_msg "Failed to stop running server, so refusing to try to start."
       exit 1
@@ -273,10 +271,10 @@ case "$mode" in
     ;;
 
   'reload'|'force-reload')
-    if test -s "$mysqld_pid_file_path" ; then
-      read mysqld_pid <  "$mysqld_pid_file_path"
-      kill -HUP $mysqld_pid && log_success_msg "Reloading service MySQL"
-      touch "$mysqld_pid_file_path"
+    if test -s "${mysqld_pid_file_path}" ; then
+      read mysqld_pid <  "${mysqld_pid_file_path}"
+      kill -HUP ${mysqld_pid} && log_success_msg "Reloading service MySQL"
+      touch "${mysqld_pid_file_path}"
     else
       log_failure_msg "MySQL PID file could not be found!"
       exit 1
@@ -284,10 +282,10 @@ case "$mode" in
     ;;
   'status')
     # First, check to see if pid file exists
-    if test -s "$mysqld_pid_file_path" ; then
-      read mysqld_pid < "$mysqld_pid_file_path"
-      if kill -0 $mysqld_pid 2>/dev/null ; then
-        log_success_msg "MySQL running ($mysqld_pid)"
+    if test -s "${mysqld_pid_file_path}" ; then
+      read mysqld_pid < "${mysqld_pid_file_path}"
+      if kill -0 ${mysqld_pid} 2>/dev/null ; then
+        log_success_msg "MySQL running (${mysqld_pid})"
         exit 0
       else
         log_failure_msg "MySQL is not running, but PID file exists"
@@ -296,9 +294,9 @@ case "$mode" in
     else
       # Try to find appropriate mysqld process
       mysqld_pid=`pidof $libexecdir/mysqld`
-      if test -z $mysqld_pid ; then
-        if test -f "$lock_file_path" ; then
-          log_failure_msg "MySQL is not running, but lock file ($lock_file_path) exists"
+      if test -z ${mysqld_pid} ; then
+        if test -f "${$lock_file_path}" ; then
+          log_failure_msg "MySQL is not running, but lock file (${$lock_file_path}) exists"
           exit 2
         fi
         log_failure_msg "MySQL is not running"
@@ -311,8 +309,8 @@ case "$mode" in
     ;;
     *)
       # usage
-      basename=`basename "$0"`
-      echo "Usage: $basename  {start|stop|restart|reload|force-reload|status}  [ MySQL server options ]"
+      N=/etc/init.d/$NAME
+      echo "Usage: $N  {start|stop|restart|reload|force-reload|status}"
       exit 1
     ;;
 esac
